# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classifier.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\031ai.test.classifier_client'),
  serialized_pb=_b('\n\x10\x63lassifier.proto\"\xe9\x01\n\x1c\x45lementClassificationRequest\x12\x11\n\tlabelHint\x18\x01 \x01(\t\x12G\n\relementImages\x18\x02 \x03(\x0b\x32\x30.ElementClassificationRequest.ElementImagesEntry\x12\x1b\n\x13\x63onfidenceThreshold\x18\x03 \x01(\x01\x12\x1a\n\x12\x61llowWeakerMatches\x18\x04 \x01(\x08\x1a\x34\n\x12\x45lementImagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"[\n\x1b\x45lementClassificationResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x19\n\x11\x63onfidenceForHint\x18\x03 \x01(\x01\"\xad\x01\n\x12\x43lassifiedElements\x12\x41\n\x0f\x63lassifications\x18\x01 \x03(\x0b\x32(.ClassifiedElements.ClassificationsEntry\x1aT\n\x14\x43lassificationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.ElementClassificationResult:\x02\x38\x01\x32T\n\nClassifier\x12\x46\n\x10\x43lassifyElements\x12\x1d.ElementClassificationRequest\x1a\x13.ClassifiedElementsB\x1b\n\x19\x61i.test.classifier_clientb\x06proto3')
)




_ELEMENTCLASSIFICATIONREQUEST_ELEMENTIMAGESENTRY = _descriptor.Descriptor(
  name='ElementImagesEntry',
  full_name='ElementClassificationRequest.ElementImagesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ElementClassificationRequest.ElementImagesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ElementClassificationRequest.ElementImagesEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=254,
)

_ELEMENTCLASSIFICATIONREQUEST = _descriptor.Descriptor(
  name='ElementClassificationRequest',
  full_name='ElementClassificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labelHint', full_name='ElementClassificationRequest.labelHint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elementImages', full_name='ElementClassificationRequest.elementImages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidenceThreshold', full_name='ElementClassificationRequest.confidenceThreshold', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allowWeakerMatches', full_name='ElementClassificationRequest.allowWeakerMatches', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ELEMENTCLASSIFICATIONREQUEST_ELEMENTIMAGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=254,
)


_ELEMENTCLASSIFICATIONRESULT = _descriptor.Descriptor(
  name='ElementClassificationResult',
  full_name='ElementClassificationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='ElementClassificationResult.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ElementClassificationResult.confidence', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidenceForHint', full_name='ElementClassificationResult.confidenceForHint', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=347,
)


_CLASSIFIEDELEMENTS_CLASSIFICATIONSENTRY = _descriptor.Descriptor(
  name='ClassificationsEntry',
  full_name='ClassifiedElements.ClassificationsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ClassifiedElements.ClassificationsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ClassifiedElements.ClassificationsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=523,
)

_CLASSIFIEDELEMENTS = _descriptor.Descriptor(
  name='ClassifiedElements',
  full_name='ClassifiedElements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classifications', full_name='ClassifiedElements.classifications', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLASSIFIEDELEMENTS_CLASSIFICATIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=523,
)

_ELEMENTCLASSIFICATIONREQUEST_ELEMENTIMAGESENTRY.containing_type = _ELEMENTCLASSIFICATIONREQUEST
_ELEMENTCLASSIFICATIONREQUEST.fields_by_name['elementImages'].message_type = _ELEMENTCLASSIFICATIONREQUEST_ELEMENTIMAGESENTRY
_CLASSIFIEDELEMENTS_CLASSIFICATIONSENTRY.fields_by_name['value'].message_type = _ELEMENTCLASSIFICATIONRESULT
_CLASSIFIEDELEMENTS_CLASSIFICATIONSENTRY.containing_type = _CLASSIFIEDELEMENTS
_CLASSIFIEDELEMENTS.fields_by_name['classifications'].message_type = _CLASSIFIEDELEMENTS_CLASSIFICATIONSENTRY
DESCRIPTOR.message_types_by_name['ElementClassificationRequest'] = _ELEMENTCLASSIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['ElementClassificationResult'] = _ELEMENTCLASSIFICATIONRESULT
DESCRIPTOR.message_types_by_name['ClassifiedElements'] = _CLASSIFIEDELEMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ElementClassificationRequest = _reflection.GeneratedProtocolMessageType('ElementClassificationRequest', (_message.Message,), {

  'ElementImagesEntry' : _reflection.GeneratedProtocolMessageType('ElementImagesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ELEMENTCLASSIFICATIONREQUEST_ELEMENTIMAGESENTRY,
    '__module__' : 'classifier_pb2'
    # @@protoc_insertion_point(class_scope:ElementClassificationRequest.ElementImagesEntry)
    })
  ,
  'DESCRIPTOR' : _ELEMENTCLASSIFICATIONREQUEST,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:ElementClassificationRequest)
  })
_sym_db.RegisterMessage(ElementClassificationRequest)
_sym_db.RegisterMessage(ElementClassificationRequest.ElementImagesEntry)

ElementClassificationResult = _reflection.GeneratedProtocolMessageType('ElementClassificationResult', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTCLASSIFICATIONRESULT,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:ElementClassificationResult)
  })
_sym_db.RegisterMessage(ElementClassificationResult)

ClassifiedElements = _reflection.GeneratedProtocolMessageType('ClassifiedElements', (_message.Message,), {

  'ClassificationsEntry' : _reflection.GeneratedProtocolMessageType('ClassificationsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLASSIFIEDELEMENTS_CLASSIFICATIONSENTRY,
    '__module__' : 'classifier_pb2'
    # @@protoc_insertion_point(class_scope:ClassifiedElements.ClassificationsEntry)
    })
  ,
  'DESCRIPTOR' : _CLASSIFIEDELEMENTS,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:ClassifiedElements)
  })
_sym_db.RegisterMessage(ClassifiedElements)
_sym_db.RegisterMessage(ClassifiedElements.ClassificationsEntry)


DESCRIPTOR._options = None
_ELEMENTCLASSIFICATIONREQUEST_ELEMENTIMAGESENTRY._options = None
_CLASSIFIEDELEMENTS_CLASSIFICATIONSENTRY._options = None

_CLASSIFIER = _descriptor.ServiceDescriptor(
  name='Classifier',
  full_name='Classifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=525,
  serialized_end=609,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClassifyElements',
    full_name='Classifier.ClassifyElements',
    index=0,
    containing_service=None,
    input_type=_ELEMENTCLASSIFICATIONREQUEST,
    output_type=_CLASSIFIEDELEMENTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLASSIFIER)

DESCRIPTOR.services_by_name['Classifier'] = _CLASSIFIER

# @@protoc_insertion_point(module_scope)
