# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import classifier_pb2 as classifier__pb2


class ClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ClassifyElements = channel.unary_unary(
        '/Classifier/ClassifyElements',
        request_serializer=classifier__pb2.ElementClassificationRequest.SerializeToString,
        response_deserializer=classifier__pb2.ClassifiedElements.FromString,
        )


class ClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ClassifyElements(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ClassifyElements': grpc.unary_unary_rpc_method_handler(
          servicer.ClassifyElements,
          request_deserializer=classifier__pb2.ElementClassificationRequest.FromString,
          response_serializer=classifier__pb2.ClassifiedElements.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Classifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
