# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("classifier.proto", :syntax => :proto3) do
    add_message "ElementClassificationRequest" do
      optional :labelHint, :string, 1
      map :elementImages, :string, :bytes, 2
      optional :confidenceThreshold, :double, 3
      optional :allowWeakerMatches, :bool, 4
    end
    add_message "ElementClassificationResult" do
      optional :label, :string, 1
      optional :confidence, :double, 2
      optional :confidenceForHint, :double, 3
    end
    add_message "ClassifiedElements" do
      map :classifications, :string, :message, 1, "ElementClassificationResult"
    end
  end
end

ElementClassificationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ElementClassificationRequest").msgclass
ElementClassificationResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("ElementClassificationResult").msgclass
ClassifiedElements = Google::Protobuf::DescriptorPool.generated_pool.lookup("ClassifiedElements").msgclass
